/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * interfaz.java
 *
 * Created on 23/11/2012, 15:06:27
 */
package proyectofinal;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos J. Peña Pollastri "Markuz Cífer"
 *          Stefano Tagliaferri
 */
public class interfaz extends javax.swing.JFrame {
    
    private ListadePersonajes LP=new ListadePersonajes();
    private Batalla batalla;
    private ArchivoPersonajes AP = new ArchivoPersonajes();
    

    /** Creates new form interfaz */
    public interfaz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        HP = new javax.swing.JTextField();
        DEF = new javax.swing.JTextField();
        EVA = new javax.swing.JTextField();
        PRE = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextPane();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        SNombre1 = new javax.swing.JTextField();
        SNombre2 = new javax.swing.JTextField();
        SNombre3 = new javax.swing.JTextField();
        PP3 = new javax.swing.JTextField();
        EFECT3 = new javax.swing.JTextField();
        DAÑO3 = new javax.swing.JTextField();
        DAÑO2 = new javax.swing.JTextField();
        EFECT2 = new javax.swing.JTextField();
        PP2 = new javax.swing.JTextField();
        EFECT1 = new javax.swing.JTextField();
        DAÑO1 = new javax.swing.JTextField();
        PP1 = new javax.swing.JTextField();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        ATQ = new javax.swing.JTextField();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();
        BotonIniciar = new javax.swing.JButton();
        BotonVer = new javax.swing.JButton();
        exportarListabtn = new javax.swing.JButton();
        ImportarListabtn = new javax.swing.JButton();
        VaciarLista = new javax.swing.JButton();
        Añadir2 = new javax.swing.JButton();
        BotonBorrarPorNombre = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Resultados2 = new javax.swing.JTextArea();
        Tutorial = new javax.swing.JButton();
        botonAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPActionPerformed(evt);
            }
        });

        DEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEFActionPerformed(evt);
            }
        });

        EVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVAActionPerformed(evt);
            }
        });

        PRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREActionPerformed(evt);
            }
        });

        label1.setText("Personaje");

        label3.setText("HP");

        label4.setText("Ataque");

        label5.setText("Defensa");

        label6.setText("Evación");

        label7.setText("Presición");

        jScrollPane1.setViewportView(Resultados);

        label8.setText("Habilidad 1");

        label9.setText("Habilidad 2");

        label10.setText("Habilidad 3");

        label11.setText("Nombre");

        label12.setText("Nombre");

        label13.setText("Nombre");

        SNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNombre1ActionPerformed(evt);
            }
        });

        SNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNombre2ActionPerformed(evt);
            }
        });

        SNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNombre3ActionPerformed(evt);
            }
        });

        PP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PP3ActionPerformed(evt);
            }
        });

        EFECT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EFECT3ActionPerformed(evt);
            }
        });

        DAÑO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAÑO3ActionPerformed(evt);
            }
        });

        DAÑO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAÑO2ActionPerformed(evt);
            }
        });

        EFECT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EFECT2ActionPerformed(evt);
            }
        });

        PP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PP2ActionPerformed(evt);
            }
        });

        EFECT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EFECT1ActionPerformed(evt);
            }
        });

        DAÑO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAÑO1ActionPerformed(evt);
            }
        });

        PP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PP1ActionPerformed(evt);
            }
        });

        label14.setText("Daño");

        label15.setText("Daño");

        label16.setText("Daño");

        label17.setText("Nombre");

        ATQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATQActionPerformed(evt);
            }
        });

        label18.setText("Efectividad");

        label19.setText("Efectividad");

        label20.setText("Efectividad");

        label21.setText("PP");

        label22.setText("PP");

        label23.setText("PP");

        BotonIniciar.setText("Iniciar batalla");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });

        BotonVer.setText("Ver la lista");
        BotonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerActionPerformed(evt);
            }
        });

        exportarListabtn.setText("Guardar Lista");
        exportarListabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarListabtnActionPerformed(evt);
            }
        });

        ImportarListabtn.setText("Cargar Lista");
        ImportarListabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarListabtnActionPerformed(evt);
            }
        });

        VaciarLista.setText("Vaciar Lista");
        VaciarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaciarListaActionPerformed(evt);
            }
        });

        Añadir2.setText("Añadir");
        Añadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Añadir2ActionPerformed(evt);
            }
        });

        BotonBorrarPorNombre.setText("Borrar por nombre");
        BotonBorrarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarPorNombreActionPerformed(evt);
            }
        });

        Resultados2.setColumns(20);
        Resultados2.setRows(5);
        jScrollPane2.setViewportView(Resultados2);

        Tutorial.setText("Tutorial");
        Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialActionPerformed(evt);
            }
        });

        botonAbout.setText("About");
        botonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAboutActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(Añadir2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26)
                        .add(BotonBorrarPorNombre)
                        .add(23, 23, 23)
                        .add(BotonVer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26)
                        .add(VaciarLista, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(BotonIniciar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26)
                        .add(exportarListabtn)
                        .add(33, 33, 33)
                        .add(ImportarListabtn)
                        .add(158, 158, 158))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(102, 102, 102)
                                .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(200, 200, 200)
                                .add(label8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(label7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, label6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, label5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(label17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(PRE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(EVA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(DEF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(label4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(HP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(ATQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(75, 75, 75)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(label11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(label14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(label18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(EFECT1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(SNombre1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(DAÑO1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(77, 77, 77)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(124, 124, 124)
                                .add(label9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(label13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(24, 24, 24)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(SNombre2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(DAÑO2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(EFECT2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PP2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(91, 91, 91)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(35, 35, 35)
                                .add(label10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(label12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(PP3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(SNombre3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(EFECT3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(DAÑO3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(33, 33, 33))))
            .add(layout.createSequentialGroup()
                .add(129, 129, 129)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 504, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 506, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 43, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(183, 183, 183)
                                .add(Tutorial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(209, 209, 209)
                                .add(botonAbout)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(24, 24, 24)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(label11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(SNombre1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(DAÑO1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(EFECT1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(label21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ATQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(label5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(DEF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(HP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(PP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(EVA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(PRE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(layout.createSequentialGroup()
                        .add(label10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(24, 24, 24)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(label12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(SNombre3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(DAÑO3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(EFECT3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PP3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(label9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(label13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(SNombre2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(DAÑO2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(EFECT2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(label19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PP2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 45, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Añadir2)
                    .add(BotonVer)
                    .add(VaciarLista)
                    .add(BotonIniciar)
                    .add(exportarListabtn)
                    .add(ImportarListabtn)
                    .add(BotonBorrarPorNombre))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(Tutorial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(botonAbout)))
                .add(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HPActionPerformed

    private void DEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEFActionPerformed

    private void EVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EVAActionPerformed

    private void PREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PREActionPerformed

    private void SNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNombre1ActionPerformed

    private void SNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNombre2ActionPerformed

    private void SNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNombre3ActionPerformed

    private void PP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PP3ActionPerformed

    private void EFECT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EFECT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EFECT3ActionPerformed

    private void DAÑO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAÑO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAÑO3ActionPerformed

    private void DAÑO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAÑO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAÑO2ActionPerformed

    private void EFECT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EFECT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EFECT2ActionPerformed

    private void PP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PP2ActionPerformed

    private void EFECT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EFECT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EFECT1ActionPerformed

    private void DAÑO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAÑO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAÑO1ActionPerformed

    private void PP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PP1ActionPerformed

    private void ATQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATQActionPerformed

    private void BotonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerActionPerformed
        try{
        Resultados.setText(LP.toString());
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(rootPane, "Error: la lista puede estar vacia ");
        }
    }//GEN-LAST:event_BotonVerActionPerformed

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
      try{
           StringBuilder SB= new StringBuilder("");
            batalla=new Batalla(LP);
                //int contadorVivos=LP.contadorPersonajesVivos();
        
            if(LP.getTamaño()>=2){
                //while(contadorVivos>1){
                    SB.append(batalla.desarrolloBatalla());
                    //contadorVivos=LP.contadorPersonajesVivos();
               //}
                Resultados.setText(SB.toString());
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Agregue más de un personaje");
       }
       catch(Exception E){
           JOptionPane.showMessageDialog(rootPane, "ERROR DESCONOCIDO");
       }
        
    }//GEN-LAST:event_BotonIniciarActionPerformed

    private void exportarListabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarListabtnActionPerformed

        boolean flag;
        flag = AP.ExportarLista(LP);
        if(flag == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Error al exportar lista");
        }
        
        
        
    }//GEN-LAST:event_exportarListabtnActionPerformed

    private void ImportarListabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarListabtnActionPerformed
        // TODO add your handling code here:
        LP = AP.ImportarLista();
        
        
    }//GEN-LAST:event_ImportarListabtnActionPerformed

    private void VaciarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaciarListaActionPerformed
        // TODO add your handling code here:
        try{LP.borrarLista();}
        catch(Exception E){JOptionPane.showMessageDialog(rootPane, "ERROR DESCONOCIDO");}
        
    }//GEN-LAST:event_VaciarListaActionPerformed

    private void Añadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir2ActionPerformed
        try{
            
            //Atributos del personaje.
            String Nombre=nombre.getText();
            float hp= Float.parseFloat(HP.getText());
            float ataque=Float.parseFloat(ATQ.getText());
            float defensa=Float.parseFloat(DEF.getText());
            float evacion=Float.parseFloat(EVA.getText());
            float presicion=Float.parseFloat(PRE.getText());
            
            //atributos de la skill 1
            String Snombre1=SNombre1.getText();
            float daño1=Float.parseFloat(DAÑO1.getText());
            float efectividad1=Float.parseFloat(EFECT1.getText());
            int pp1= Integer.parseInt(PP1.getText());
            
            //Atributos de la skill 2
            String Snombre2=SNombre2.getText();
            float daño2=Float.parseFloat(DAÑO2.getText());
            float efectividad2=Float.parseFloat(EFECT2.getText());
            int pp2= Integer.parseInt(PP2.getText());
            
            //Atributos de la skill 3
            String Snombre3=SNombre3.getText();
            float daño3=Float.parseFloat(DAÑO3.getText());
            float efectividad3=Float.parseFloat(EFECT3.getText());
            int pp3= Integer.parseInt(PP3.getText());
            
            Skill S1= new Skill(Snombre1, efectividad1, pp1, daño1);
            Skill S2= new Skill(Snombre2, efectividad2, pp2, daño2);
            Skill S3= new Skill(Snombre3, efectividad3, pp3, daño3);
            
            Personaje nuevo = new Personaje(hp ,ataque, defensa, evacion, presicion, Nombre, S1, S2, S3);
            
            LP.agregarPersonaje(nuevo);
            
            //Se reinician los casilleros.
            nombre.setText("");
            HP.setText("");
            ATQ.setText("");
            DEF.setText("");
            PRE.setText("");
            EVA.setText("");
            SNombre1.setText("");
            SNombre2.setText("");
            SNombre3.setText("");
            DAÑO1.setText("");
            DAÑO2.setText("");
            DAÑO3.setText("");
            EFECT1.setText("");
            EFECT2.setText("");
            EFECT3.setText("");
            PP1.setText("");
            PP2.setText("");
            PP3.setText("");
       }
       catch(Exception E){
           JOptionPane.showMessageDialog(rootPane, "Error: Complete todos los campos o ingrese datos validos");
           
       }
       
        
    }//GEN-LAST:event_Añadir2ActionPerformed

    private void BotonBorrarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarPorNombreActionPerformed
        // TODO add your handling code here:
        try
        {
             String Aux;
             Aux = nombre.getText();
             LP.eliminarPersonajePorNombre(Aux);
        }
        catch(Exception E)
        {
            JOptionPane.showMessageDialog(rootPane, "Error desconocido ");
        }
    }//GEN-LAST:event_BotonBorrarPorNombreActionPerformed

    private void TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialActionPerformed
        // TODO add your handling code here:
        String Tutorial = "Este programa es un simulador de batallas entre personajes" +"\n" + "Los cuales poseen habilidades y atributos que son cargados por el usuario" + "\n" +
                "No hay limites para la cantidad de personajes que pueden participar en una batalla"+"\n"+"El programa realiza batallas individuales entre 2 personajes al azar"+"\n"+
                "los personajes usan sus habilidades al azar, y basandose en sus atributos" +"\n"+ "se decide si aciertan o no" + "\n" + "Cuando un personaje pierde todos sus HP, queda derrotado y no participa mas en la batalla"+ "\n" +
                "El programa termina la ejecucion cuando queda solo un personaje en pie";
        Resultados2.setText(Tutorial);
    }//GEN-LAST:event_TutorialActionPerformed

    private void botonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAboutActionPerformed
        // TODO add your handling code here:
        String msj = "By \nMarcos P. Pollastri\n&\nStefano Tagliaferri"
        + " \n\nThis program is free software: you can redistribute it and/or modify\n" +
"    it under the terms of the GNU General Public License as published by\n" +
"    the Free Software Foundation, either version 3 of the License, or\n" +
"    (at your option) any later version.\n" +
"\n" +
"    This program is distributed in the hope that it will be useful,\n" +
"    but WITHOUT ANY WARRANTY; without even the implied warranty of\n" +
"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" +
"    GNU General Public License for more details.\n" +
"\n" +
"    You should have received a copy of the GNU General Public License\n" +
"    along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
                + "\nYou can download the sourcecode from:\nhttps://github.com/marcosppollastri/SimuladorDePeleas";
        JOptionPane.showMessageDialog(rootPane, msj);
    }//GEN-LAST:event_botonAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATQ;
    private javax.swing.JButton Añadir2;
    private javax.swing.JButton BotonBorrarPorNombre;
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JButton BotonVer;
    private javax.swing.JTextField DAÑO1;
    private javax.swing.JTextField DAÑO2;
    private javax.swing.JTextField DAÑO3;
    private javax.swing.JTextField DEF;
    private javax.swing.JTextField EFECT1;
    private javax.swing.JTextField EFECT2;
    private javax.swing.JTextField EFECT3;
    private javax.swing.JTextField EVA;
    private javax.swing.JTextField HP;
    private javax.swing.JButton ImportarListabtn;
    private javax.swing.JTextField PP1;
    private javax.swing.JTextField PP2;
    private javax.swing.JTextField PP3;
    private javax.swing.JTextField PRE;
    private javax.swing.JTextPane Resultados;
    private javax.swing.JTextArea Resultados2;
    private javax.swing.JTextField SNombre1;
    private javax.swing.JTextField SNombre2;
    private javax.swing.JTextField SNombre3;
    private javax.swing.JButton Tutorial;
    private javax.swing.JButton VaciarLista;
    private javax.swing.JButton botonAbout;
    private javax.swing.JButton exportarListabtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
